### ISSUE TITLE
Logic issue for `llm.openai/vector.enabled()`

### ISSUE THREAD

**Issue by edwardcqian** [grafana/grafana-llm-app#120]
Currently we returning the healthcheck details when we call `llm.openai/vector.enabled()`.

But we check `!enabled` which always returns true.

We should change the `enabled` logic in `grafana-experimental`, so it return the correct value.

We should maybe change the current `enabled` logic to be `healthCheckDetails`.

**Comment by yoziru** [comment]
Moving to https://github.com/grafana/grafana-experimental/issues/95
