### ISSUE TITLE
Please add support for Ollama

### ISSUE THREAD

**Issue by ntimo** [grafana/grafana-llm-app#162]
By supporting Ollama it would be possible to use locally hosted LLMs which, would be quite privacy friendly. I think this would pair quite nicely with Grafana’s mission.

https://github.com/jmorganca/ollama

**Comment by tedraymond** [comment]
Support for all open source llms

**Comment by tedraymond** [comment]
support works for local llm environments. the issue i'm seeing now, is it appears the Auto-Gen function in grafana is timing out before the local LLM agent has a chance to respond

**Comment by tedraymond** [comment]
Im thinking at least increasing the timeout. Grafana errors out before a local llm has time to respond. Of course we could increase performance on the local llm host but may not he the case for everyone.

For the different models, maybe having an edit prompt fields so a user can define the instructions to be sent along with the other parameters, tokens, temperature, etc..

**Comment by phyzical** [comment]
@tedraymond did you happen to find a way to increase the timeout yet? 10 seconds is just too little for my 2060 ;(
