### ISSUE TITLE
Plugin installed but not appear in Grafana

### ISSUE THREAD

**Issue by klinux** [grafana/grafana-llm-app#476]
Hello,

I've installed the plugin, everything is configured and enabled, but the LLM options isn't working, Auto-generate is not available in grafana, and there's not error in logs.

**plugin**: 0.11.0
**grafana**: 10.2.9

**Comment by sd2k** [comment]
Hi @klinux. 10.2.9 is a little old now so I think you may need to enable the `dashgpt` feature toggle to get the auto-generate panel title/description features. Can you give that a go using the [Configure Grafana docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#feature_toggles) and the [Feature Toggles docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/) and let me know if it works?

(You can also enable the feature using environment variables: `GF_FEATURE_TOGGLES_ENABLE=dashgpt`)

**Comment by klinux** [comment]
it works, thank you
