### ISSUE TITLE
Propagate error messages from API calls to frontend in OAI

### ISSUE THREAD

**Issue by SandersAaronD** [grafana/grafana-llm-app#74]
References this: https://github.com/grafana/grafana/issues/75501

For streaming responses from OAI, we need to propagate errors to the frontend so that API requests don't fail silently.

**Comment by sd2k** [comment]
From a bit of playing around the only way to do this is to avoid returning an `error` from `RunStream` and instead call `sender.SendJSON()` with an error-like payload, which we'll then need to handle in `@grafana/experimental`.
